// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-HpAD2tON4qiyFM0fjki8eloxs2ferEw',
    appId: '1:287735339821:web:fa7dac23378b6c8594d1a4',
    messagingSenderId: '287735339821',
    projectId: 'store-app-f4462',
    authDomain: 'store-app-f4462.firebaseapp.com',
    storageBucket: 'store-app-f4462.appspot.com',
    measurementId: 'G-6WKC2V6SXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEY5P3_7279xsZlpXWk9nM3SqEpv-KIl0',
    appId: '1:287735339821:android:2dc21ffc76af9cf294d1a4',
    messagingSenderId: '287735339821',
    projectId: 'store-app-f4462',
    storageBucket: 'store-app-f4462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeBxypvUZ2XAuj8CS0I6syHCkrfklDPK8',
    appId: '1:287735339821:ios:fca5a1cb4db5b37b94d1a4',
    messagingSenderId: '287735339821',
    projectId: 'store-app-f4462',
    storageBucket: 'store-app-f4462.appspot.com',
    iosClientId: '287735339821-0r8q6eke2lot80vie83fj9nnp006q9m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeBxypvUZ2XAuj8CS0I6syHCkrfklDPK8',
    appId: '1:287735339821:ios:ba0e04e77bb2e83294d1a4',
    messagingSenderId: '287735339821',
    projectId: 'store-app-f4462',
    storageBucket: 'store-app-f4462.appspot.com',
    iosClientId: '287735339821-ffi6kigr4mohp1uf36asc1353kk4e6ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
